# Gunakan base image Go yang berbasis Alpine untuk membangun aplikasi
FROM golang:1.23.2

# Buat direktori kerja di container
WORKDIR /app

# Salin go.mod dan go.sum, lalu install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Salin kode aplikasi
COPY . .

# Menentukan port yang akan digunakan
EXPOSE 3000

# Jalankan aplikasi saat container dimulai
CMD ["go", "run", "main.go"]
